services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1234/health"]
      interval: 30s
      timeout: 10s
      retries: 3
