apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-mock-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: lz-ml
  source:
    repoURL: git@bitbucket.org:likezero/lz-ml-argo-test.git
    targetRevision: HEAD
    path: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
